'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';

interface ChatBubble {
    sender: 'user' | 'ai';
    text: string;
    romaji?: string;
    english?: string;
}

interface ScenarioDetails {
    title: string;
    context: string;
    aiCharacterName: string;
    aiCharacterRole: string;
    learningGoals: string;
}

export default function AI_Dojo_Chatroom() {
    const params = useParams();
    const router = useRouter();
    const scenarioId = Number(params.id);

    const [scenario, setScenario] = useState<ScenarioDetails | null>(null);
    const [messages, setMessages] = useState<ChatBubble[]>([]);
    const [inputMessage, setInputMessage] = useState('');
    const [turn, setTurn] = useState(1);
    const [loading, setLoading] = useState(false);
    const [initLoading, setInitLoading] = useState(true);
    const [finalEvaluation, setFinalEvaluation] = useState<any | null>(null);

    // 1. Automatically fetch the exact scenario properties from the database on mount
    useEffect(() => {
        async function loadScenarioContext() {
            try {
                const res = await fetch(`/api/scenario/${scenarioId}`);
                const data = await res.json();

                if (data.success) {
                    setScenario(data.scenario);
                    // Seed the initial structural greeting from the character configuration dynamically
                    setMessages([
                        {
                            sender: 'ai',
                            text: `こんにちは！私は${data.scenario.aiCharacterName}です。`,
                            romaji: `Konnichiwa! Watashi wa ${data.scenario.aiCharacterName} desu.`,
                            english: `Hello! I am ${data.scenario.aiCharacterName}.`
                        }
                    ]);
                }
            } catch (err) {
                console.error("Failed loading target scenario metrics:", err);
            } finally {
                setInitLoading(false);
            }
        }
        loadScenarioContext();
    }, [scenarioId]);

    const handleSendMessage = async () => {
        if (!inputMessage.trim() || loading) return;

        setLoading(true);
        const dynamicUserTurn = inputMessage;
        setMessages(prev => [...prev, { sender: 'user', text: dynamicUserTurn }]);
        setInputMessage('');

        try {
            const response = await fetch('/api/chat', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    userId: 1, // Relational target fallback tracking index
                    scenarioId: scenarioId,
                    userRawInputJp: dynamicUserTurn,
                    currentTurnNo: turn
                })
            });

            const data = await response.json();

            if (data.success) {
                // Update user message block with the ML breakdown properties
                setMessages(prev => {
                    const base = [...prev];
                    base[base.length - 1] = {
                        sender: 'user',
                        text: dynamicUserTurn,
                        romaji: data.analysis.messageRomaji,
                        english: data.analysis.messageEn
                    };
                    return base;
                });

                // Instantly push the custom dynamic AI reply text generated by Gemini
                setMessages(prev => [
                    ...prev,
                    {
                        sender: 'ai',
                        text: data.analysis.nextAiReply.japanese,
                        romaji: data.analysis.nextAiReply.romaji,
                        english: data.analysis.nextAiReply.english
                    }
                ]);

                if (turn >= 3) {
                    setFinalEvaluation(data.analysis);
                } else {
                    setTurn(prev => prev + 1);
                }
            }
        } catch (err) {
            console.error('Chat loop tracking exception:', err);
        } finally {
            setLoading(false);
        }
    };

    if (initLoading) return <div style={{ textAlign: 'center', padding: '50px' }}>Loading Dojo Scenario Context...</div>;
    if (!scenario) return <div style={{ textAlign: 'center', padding: '50px' }}>Scenario not found.</div>;

    return (
        <div style={{ maxWidth: '650px', margin: '40px auto', padding: '20px', fontFamily: 'sans-serif' }}>
            <button onClick={() => router.push('/')} style={{ background: 'none', border: 'none', color: '#0070f3', cursor: 'pointer', marginBottom: '10px', fontSize: '1rem' }}>
                &larr; Back to Roleplays
            </button>

            <h2 style={{ borderBottom: '2px solid #333', paddingBottom: '10px', margin: '0 0 5px 0' }}>{scenario.title}</h2>
            <p style={{ color: '#666', fontSize: '0.9rem', margin: '0 0 20px 0' }}>Roleplay character: <strong>{scenario.aiCharacterName}</strong> — {scenario.aiCharacterRole}</p>

            {/* Dynamic Conversational Scrolling Window Panel */}
            <div style={{ minHeight: '350px', background: '#f7fafc', padding: '20px', borderRadius: '12px', margin: '20px 0', border: '1px solid #e2e8f0' }}>
                {messages.map((msg, i) => (
                    <div key={i} style={{ textAlign: msg.sender === 'user' ? 'right' : 'left', margin: '15px 0' }}>
                        <div style={{
                            display: 'inline-block',
                            background: msg.sender === 'user' ? '#0070f3' : '#edf2f7',
                            color: msg.sender === 'user' ? '#fff' : '#2d3748',
                            padding: '12px 16px',
                            borderRadius: '14px',
                            fontSize: '16px',
                            maxWidth: '80%',
                            textAlign: 'left'
                        }}>
                            <strong>{msg.text}</strong>
                            {(msg.romaji || msg.english) && (
                                <div style={{ opacity: 0.8, fontSize: '12px', marginTop: '6px', borderTop: '1px solid rgba(0,0,0,0.08)', paddingTop: '6px' }}>
                                    <i>{msg.romaji}</i> <br /> {msg.english}
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Input controls layout wrapper */}
            {!finalEvaluation ? (
                <div style={{ display: 'flex', gap: '10px' }}>
                    <input type="text" value={inputMessage} onChange={(e) => setInputMessage(e.target.value)} placeholder={`Respond to ${scenario.aiCharacterName} in Japanese...`} style={{ flex: 1, padding: '14px', fontSize: '15px', borderRadius: '6px', border: '1px solid #cbd5e0' }} onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}/>
                    <button onClick={handleSendMessage} disabled={loading} style={{ padding: '0 28px', background: '#000', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
                        {loading ? 'Processing...' : 'Send'}
                    </button>
                </div>
            ) : (
                /* Evaluation Breakdown Scorecard Display */
                <div style={{ background: '#f0fff4', border: '1px solid #38a169', padding: '24px', borderRadius: '12px', marginTop: '20px' }}>
                    <h3 style={{ color: '#22543d', marginTop: 0, borderBottom: '1px solid #c6f6d5', paddingBottom: '8px' }}>📊 Performance Grading Scorecard</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', margin: '15px 0' }}>
                        <p style={{ margin: 0 }}><strong>Vocabulary:</strong> {finalEvaluation.scores.vocabulary}/30</p>
                        <p style={{ margin: 0 }}><strong>Grammar:</strong> {finalEvaluation.scores.grammar}/25</p>
                        <p style={{ margin: 0 }}><strong>Fluency:</strong> {finalEvaluation.scores.fluency}/20</p>
                        <p style={{ margin: 0 }}><strong>Cultural Rapport:</strong> {finalEvaluation.scores.cultural}/15</p>
                        <p style={{ margin: 0 }}><strong>Task Target:</strong> {finalEvaluation.scores.task}/10</p>
                    </div>
                    <div style={{ background: '#fff', padding: '16px', borderRadius: '6px', marginTop: '15px', borderLeft: '4px solid #38a169', boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
                        <strong>AI Sensei Evaluation:</strong> {finalEvaluation.feedback}
                    </div>
                </div>
            )}
        </div>
    );
}