export interface LanguageConfig {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  bcp47: { stt: string; tts: string };
  azureVoice: { female: string; male: string };
  hasPhonetic: boolean;
  ttsSupported: boolean;
}

export const TARGET_LANGUAGES: LanguageConfig[] = [
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    bcp47: { stt: 'ja-JP', tts: 'ja-JP' },
    azureVoice: { female: 'ja-JP-NanamiNeural', male: 'ja-JP-KeitaNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    bcp47: { stt: 'en-US', tts: 'en-US' },
    azureVoice: { female: 'en-US-JennyNeural', male: 'en-US-GuyNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    bcp47: { stt: 'fr-FR', tts: 'fr-FR' },
    azureVoice: { female: 'fr-FR-DeniseNeural', male: 'fr-FR-HenriNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    bcp47: { stt: 'de-DE', tts: 'de-DE' },
    azureVoice: { female: 'de-DE-KatjaNeural', male: 'de-DE-KillianNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    bcp47: { stt: 'es-ES', tts: 'es-ES' },
    azureVoice: { female: 'es-ES-ElviraNeural', male: 'es-ES-AlvaroNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    bcp47: { stt: 'ru-RU', tts: 'ru-RU' },
    azureVoice: { female: 'ru-RU-SvetlanaNeural', male: 'ru-RU-DmitryNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇪🇬',
    bcp47: { stt: 'ar-EG', tts: 'ar-EG' },
    azureVoice: { female: 'ar-EG-SalmaNeural', male: 'ar-EG-KhalidNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'sw',
    name: 'Kiswahili',
    nativeName: 'Kiswahili',
    flag: '🇰🇪',
    bcp47: { stt: 'sw-KE', tts: 'sw-KE' },
    azureVoice: { female: 'sw-KE-ZuriNeural', male: 'sw-KE-RafikiNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'lg',
    name: 'Luganda',
    nativeName: 'Luganda',
    flag: '🇺🇬',
    // Intentional stub: no Azure neural voice exists for Luganda yet, so STT/TTS
    // reuse en-US as a stand-in and ttsSupported is false (the UI hides TTS for
    // this language instead of attempting playback with a wrong voice).
    bcp47: { stt: 'en-US', tts: 'en-US' },
    azureVoice: { female: 'en-US-JennyNeural', male: 'en-US-GuyNeural' },
    hasPhonetic: false,
    ttsSupported: false,
  },
  {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    flag: '🇧🇷',
    bcp47: { stt: 'pt-BR', tts: 'pt-BR' },
    azureVoice: { female: 'pt-BR-FranciscaNeural', male: 'pt-BR-AntonioNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    bcp47: { stt: 'it-IT', tts: 'it-IT' },
    azureVoice: { female: 'it-IT-ElsaNeural', male: 'it-IT-DiegoNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    flag: '🇳🇱',
    bcp47: { stt: 'nl-NL', tts: 'nl-NL' },
    azureVoice: { female: 'nl-NL-ColetteNeural', male: 'nl-NL-MaartenNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    bcp47: { stt: 'tr-TR', tts: 'tr-TR' },
    azureVoice: { female: 'tr-TR-EmelNeural', male: 'tr-TR-AtillaNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    flag: '🇵🇱',
    bcp47: { stt: 'pl-PL', tts: 'pl-PL' },
    azureVoice: { female: 'pl-PL-ZofiaNeural', male: 'pl-PL-MarekNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    flag: '🇺🇦',
    bcp47: { stt: 'uk-UA', tts: 'uk-UA' },
    azureVoice: { female: 'uk-UA-PolinaNeural', male: 'uk-UA-OstapNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    flag: '🇬🇷',
    bcp47: { stt: 'el-GR', tts: 'el-GR' },
    azureVoice: { female: 'el-GR-AthinaNeural', male: 'el-GR-NestorasNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    flag: '🇮🇱',
    bcp47: { stt: 'he-IL', tts: 'he-IL' },
    azureVoice: { female: 'he-IL-HilaNeural', male: 'he-IL-AvriNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'fa',
    name: 'Persian (Farsi)',
    nativeName: 'فارسی',
    flag: '🇮🇷',
    bcp47: { stt: 'fa-IR', tts: 'fa-IR' },
    azureVoice: { female: 'fa-IR-DilaraNeural', male: 'fa-IR-FaridNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    bcp47: { stt: 'hi-IN', tts: 'hi-IN' },
    azureVoice: { female: 'hi-IN-SwaraNeural', male: 'hi-IN-MadhurNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇧🇩',
    bcp47: { stt: 'bn-BD', tts: 'bn-BD' },
    azureVoice: { female: 'bn-BD-NabanitaNeural', male: 'bn-BD-PradeepNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇵🇰',
    bcp47: { stt: 'ur-PK', tts: 'ur-PK' },
    azureVoice: { female: 'ur-PK-UzmaNeural', male: 'ur-PK-AsadNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'zh',
    name: 'Chinese (Mandarin)',
    nativeName: '中文',
    flag: '🇨🇳',
    bcp47: { stt: 'zh-CN', tts: 'zh-CN' },
    azureVoice: { female: 'zh-CN-XiaoxiaoNeural', male: 'zh-CN-YunxiNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    bcp47: { stt: 'ko-KR', tts: 'ko-KR' },
    azureVoice: { female: 'ko-KR-SunHiNeural', male: 'ko-KR-InJoonNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    flag: '🇹🇭',
    bcp47: { stt: 'th-TH', tts: 'th-TH' },
    azureVoice: { female: 'th-TH-PremwadeeNeural', male: 'th-TH-NiwatNeural' },
    hasPhonetic: true,
    ttsSupported: true,
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    bcp47: { stt: 'vi-VN', tts: 'vi-VN' },
    azureVoice: { female: 'vi-VN-HoaiMyNeural', male: 'vi-VN-NamMinhNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'tl',
    name: 'Filipino',
    nativeName: 'Filipino',
    flag: '🇵🇭',
    bcp47: { stt: 'tl-PH', tts: 'tl-PH' },
    azureVoice: { female: 'tl-PH-BlessicaNeural', male: 'tl-PH-AngeloNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    flag: '🇲🇾',
    bcp47: { stt: 'ms-MY', tts: 'ms-MY' },
    azureVoice: { female: 'ms-MY-YasminNeural', male: 'ms-MY-OsmanNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    flag: '🇮🇩',
    bcp47: { stt: 'id-ID', tts: 'id-ID' },
    azureVoice: { female: 'id-ID-GadisNeural', male: 'id-ID-ArdiNeural' },
    hasPhonetic: false,
    ttsSupported: true,
  },
  {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ខ្មែរ',
    flag: '🇰🇭',
    // Intentional stubs for km/my/lo: no Azure neural voices exist for these
    // languages yet, so they share en-US fallback voices and mark
    // ttsSupported: false. Until real voices are wired up the UI must never
    // attempt TTS playback for them.
    bcp47: { stt: 'km-KH', tts: 'km-KH' },
    azureVoice: { female: 'en-US-JennyNeural', male: 'en-US-GuyNeural' },
    hasPhonetic: true,
    ttsSupported: false,
  },
  {
    code: 'my',
    name: 'Burmese',
    nativeName: 'မြန်မာ',
    flag: '🇲🇲',
    bcp47: { stt: 'my-MM', tts: 'my-MM' },
    azureVoice: { female: 'en-US-JennyNeural', male: 'en-US-GuyNeural' },
    hasPhonetic: true,
    ttsSupported: false,
  },
  {
    code: 'lo',
    name: 'Lao',
    nativeName: 'ລາວ',
    flag: '🇱🇦',
    bcp47: { stt: 'lo-LA', tts: 'lo-LA' },
    azureVoice: { female: 'en-US-JennyNeural', male: 'en-US-GuyNeural' },
    hasPhonetic: true,
    ttsSupported: false,
  },
];

export const NATIVE_LANGUAGES: { code: string; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'lg', name: 'Luganda', nativeName: 'Luganda' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'sw', name: 'Kiswahili', nativeName: 'Kiswahili' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'my', name: 'Burmese', nativeName: 'မြန်မာ' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ' },
];

export function getTargetLangConfig(code: string): LanguageConfig {
  return TARGET_LANGUAGES.find(l => l.code === code) ?? TARGET_LANGUAGES[0];
}

export function getNativeLangName(code: string): string {
  return NATIVE_LANGUAGES.find(l => l.code === code)?.name ?? code;
}

export function getNativeLangBcp47(code: string): string {
  const map: Record<string, string> = {
    'en': 'en-US', 'ja': 'ja-JP', 'fr': 'fr-FR', 'es': 'es-ES',
    'de': 'de-DE', 'zh': 'zh-CN', 'ko': 'ko-KR', 'pt': 'pt-BR',
    'vi': 'vi-VN', 'th': 'th-TH', 'hi': 'hi-IN', 'lg': 'en-US',
    'tl': 'tl-PH', 'km': 'km-KH', 'ms': 'ms-MY', 'id': 'id-ID',
    'my': 'my-MM', 'lo': 'lo-LA', 'bn': 'bn-BD', 'ne': 'ne-NP',
    'ru': 'ru-RU', 'ar': 'ar-EG', 'sw': 'sw-KE', 'it': 'it-IT',
    'nl': 'nl-NL', 'tr': 'tr-TR', 'ur': 'ur-PK', 'fa': 'fa-IR',
    'pl': 'pl-PL', 'uk': 'uk-UA', 'el': 'el-GR', 'he': 'he-IL',
  };
  return map[code] ?? 'en-US';
}

export function getBCP47(code: string, type: 'stt' | 'tts'): string {
  return getTargetLangConfig(code).bcp47[type];
}

export function getAzureVoice(code: string, gender: string = 'female'): string {
  const cfg = getTargetLangConfig(code);
  const key = gender === 'male' ? 'male' : 'female';
  return cfg.azureVoice[key];
}

const AZURE_VOICE_MAP: Record<string, { female: string; male: string }> = {
  'ja-JP': { female: 'ja-JP-NanamiNeural',   male: 'ja-JP-KeitaNeural' },
  'ja':    { female: 'ja-JP-NanamiNeural',   male: 'ja-JP-KeitaNeural' },
  'en-US': { female: 'en-US-JennyNeural',    male: 'en-US-GuyNeural' },
  'en':    { female: 'en-US-JennyNeural',    male: 'en-US-GuyNeural' },
  'fr-FR': { female: 'fr-FR-DeniseNeural',   male: 'fr-FR-HenriNeural' },
  'fr':    { female: 'fr-FR-DeniseNeural',   male: 'fr-FR-HenriNeural' },
  'es-ES': { female: 'es-ES-ElviraNeural',   male: 'es-ES-AlvaroNeural' },
  'es':    { female: 'es-ES-ElviraNeural',   male: 'es-ES-AlvaroNeural' },
  'de-DE': { female: 'de-DE-KatjaNeural',    male: 'de-DE-KillianNeural' },
  'de':    { female: 'de-DE-KatjaNeural',    male: 'de-DE-KillianNeural' },
  'ru-RU': { female: 'ru-RU-SvetlanaNeural', male: 'ru-RU-DmitryNeural' },
  'ru':    { female: 'ru-RU-SvetlanaNeural', male: 'ru-RU-DmitryNeural' },
  'ar-EG': { female: 'ar-EG-SalmaNeural',    male: 'ar-EG-KhalidNeural' },
  'ar':    { female: 'ar-EG-SalmaNeural',    male: 'ar-EG-KhalidNeural' },
  'sw-KE': { female: 'sw-KE-ZuriNeural',     male: 'sw-KE-RafikiNeural' },
  'sw':    { female: 'sw-KE-ZuriNeural',     male: 'sw-KE-RafikiNeural' },
  'pt-BR': { female: 'pt-BR-FranciscaNeural', male: 'pt-BR-AntonioNeural' },
  'pt':    { female: 'pt-BR-FranciscaNeural', male: 'pt-BR-AntonioNeural' },
  'it-IT': { female: 'it-IT-ElsaNeural',     male: 'it-IT-DiegoNeural' },
  'it':    { female: 'it-IT-ElsaNeural',     male: 'it-IT-DiegoNeural' },
  'nl-NL': { female: 'nl-NL-ColetteNeural',  male: 'nl-NL-MaartenNeural' },
  'nl':    { female: 'nl-NL-ColetteNeural',  male: 'nl-NL-MaartenNeural' },
  'tr-TR': { female: 'tr-TR-EmelNeural',     male: 'tr-TR-AtillaNeural' },
  'tr':    { female: 'tr-TR-EmelNeural',     male: 'tr-TR-AtillaNeural' },
  'pl-PL': { female: 'pl-PL-ZofiaNeural',    male: 'pl-PL-MarekNeural' },
  'pl':    { female: 'pl-PL-ZofiaNeural',    male: 'pl-PL-MarekNeural' },
  'uk-UA': { female: 'uk-UA-PolinaNeural',   male: 'uk-UA-OstapNeural' },
  'uk':    { female: 'uk-UA-PolinaNeural',   male: 'uk-UA-OstapNeural' },
  'el-GR': { female: 'el-GR-AthinaNeural',   male: 'el-GR-NestorasNeural' },
  'el':    { female: 'el-GR-AthinaNeural',   male: 'el-GR-NestorasNeural' },
  'he-IL': { female: 'he-IL-HilaNeural',     male: 'he-IL-AvriNeural' },
  'he':    { female: 'he-IL-HilaNeural',     male: 'he-IL-AvriNeural' },
  'fa-IR': { female: 'fa-IR-DilaraNeural',   male: 'fa-IR-FaridNeural' },
  'fa':    { female: 'fa-IR-DilaraNeural',   male: 'fa-IR-FaridNeural' },
  'hi-IN': { female: 'hi-IN-SwaraNeural',    male: 'hi-IN-MadhurNeural' },
  'hi':    { female: 'hi-IN-SwaraNeural',    male: 'hi-IN-MadhurNeural' },
  'bn-BD': { female: 'bn-BD-NabanitaNeural', male: 'bn-BD-PradeepNeural' },
  'bn':    { female: 'bn-BD-NabanitaNeural', male: 'bn-BD-PradeepNeural' },
  'ur-PK': { female: 'ur-PK-UzmaNeural',     male: 'ur-PK-AsadNeural' },
  'ur':    { female: 'ur-PK-UzmaNeural',     male: 'ur-PK-AsadNeural' },
  'zh-CN': { female: 'zh-CN-XiaoxiaoNeural', male: 'zh-CN-YunxiNeural' },
  'zh':    { female: 'zh-CN-XiaoxiaoNeural', male: 'zh-CN-YunxiNeural' },
  'ko-KR': { female: 'ko-KR-SunHiNeural',    male: 'ko-KR-InJoonNeural' },
  'ko':    { female: 'ko-KR-SunHiNeural',    male: 'ko-KR-InJoonNeural' },
  'th-TH': { female: 'th-TH-PremwadeeNeural', male: 'th-TH-NiwatNeural' },
  'th':    { female: 'th-TH-PremwadeeNeural', male: 'th-TH-NiwatNeural' },
  'vi-VN': { female: 'vi-VN-HoaiMyNeural',   male: 'vi-VN-NamMinhNeural' },
  'vi':    { female: 'vi-VN-HoaiMyNeural',   male: 'vi-VN-NamMinhNeural' },
  'tl-PH': { female: 'tl-PH-BlessicaNeural', male: 'tl-PH-AngeloNeural' },
  'tl':    { female: 'tl-PH-BlessicaNeural', male: 'tl-PH-AngeloNeural' },
  'ms-MY': { female: 'ms-MY-YasminNeural',   male: 'ms-MY-OsmanNeural' },
  'ms':    { female: 'ms-MY-YasminNeural',   male: 'ms-MY-OsmanNeural' },
  'id-ID': { female: 'id-ID-GadisNeural',    male: 'id-ID-ArdiNeural' },
  'id':    { female: 'id-ID-GadisNeural',    male: 'id-ID-ArdiNeural' },
};

export function resolveAzureVoice(bcp47: string, gender: string = 'female'): string {
  const key = gender.toLowerCase() === 'male' ? 'male' : 'female';
  return AZURE_VOICE_MAP[bcp47]?.[key]
    ?? AZURE_VOICE_MAP[bcp47?.split('-')[0]]?.[key]
    // Fallback: languages without a real Azure voice (lg, km, my, lo are
    // intentional en-US stand-ins) resolve to a generic en-US voice. Callers
    // should gate playback on ttsSupported so this default is never actually
    // used for those languages.
    ?? 'en-US-JennyNeural';
}
